esphome:
  name: ir-pult
  friendly_name: IR Pult

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

wifi:
  ssid: "Demonynok007"
  password: "25092014009"

  ap:
    ssid: "IR-Pult Fallback"
    password: "12345678"

captive_portal:
